/**
 * Style Dictionary v4 — local token pipeline (DS1).
 *
 *  - source: 本地 JSON tokens（color / type / space / motion / radius / shadow）
 *  - platforms:
 *      css      → :root CSS variables + Tailwind v4 @theme 映射
 *      js       → ESM + .d.ts（runtime 强类型取值，避免魔法色值）
 *      json     → flat JSON（Storybook token page / 调试）
 *
 * 不依赖 Figma / Tokens Studio；纯本地构建。
 */
import StyleDictionary from 'style-dictionary';

/** @type {import('style-dictionary').Config} */
const config = {
  log: {
    warnings: 'warn',
    errors: { brokenReferences: 'throw' },
  },
  source: ['src/design-system/tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/design-system/styles/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: false, selector: ':root' },
        },
        {
          destination: 'tailwind.css',
          format: 'css/tailwind-v4-theme',
          options: { outputReferences: false },
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'src/design-system/build/',
      files: [
        { destination: 'tokens.js', format: 'javascript/es6' },
        { destination: 'tokens.d.ts', format: 'typescript/module-declarations' },
      ],
    },
    json: {
      transformGroup: 'js',
      buildPath: 'src/design-system/build/',
      files: [{ destination: 'tokens.json', format: 'json/flat' }],
    },
  },
};

/**
 * Tailwind v4 @theme 生成器：
 *   把所有 tokens 暴露成 Tailwind 工具类：
 *     --color-*      → bg-/text-/border-*
 *     --font-*       → font-*
 *     --text-*       → text-*（font-size；与 Tailwind v4 默认命名空间一致）
 *     --leading-*    → leading-*（line-height）
 *     --tracking-*   → tracking-*（letter-spacing）
 *     --radius-*     → rounded-*
 *     --shadow-*     → shadow-*
 *     --motion-*     → 自定义命名空间（duration-* / ease-* / delay-*）
 *     --size-spacing-* → 自定义命名空间（spacing-*）
 *
 * 不重复声明字面量 —— 全部以 var(--xxx) 引用 :root，保证单一真相源。
 */
StyleDictionary.registerFormat({
  name: 'css/tailwind-v4-theme',
  format: ({ dictionary, options }) => {
    const lines = [
      '/**',
      ' * Tailwind v4 @theme — 自动从 :root tokens 派生。',
      ' * Do not edit directly, this file was auto-generated by Style Dictionary.',
      ' */',
      '@theme {',
    ];
    const renames = {
      'motion-duration-instant': '--duration-instant',
      'motion-duration-fast': '--duration-fast',
      'motion-duration-normal': '--duration-normal',
      'motion-duration-slow': '--duration-slow',
      'motion-duration-gentle': '--duration-gentle',
      'motion-duration-curtain': '--duration-curtain',
      'motion-duration-scene': '--duration-scene',
      'motion-easing-standard': '--ease-standard',
      'motion-easing-entrance': '--ease-entrance',
      'motion-easing-exit': '--ease-exit',
      'motion-easing-spring': '--ease-spring',
      'motion-easing-linear': '--ease-linear',
      'motion-delay-none': '--delay-none',
      'motion-delay-beat': '--delay-beat',
      'motion-delay-step': '--delay-step',
      'text-line-height-tight': '--leading-tight',
      'text-line-height-snug': '--leading-snug',
      'text-line-height-normal': '--leading-normal',
      'text-line-height-relaxed': '--leading-relaxed',
      'text-letter-tight': '--tracking-tight',
      'text-letter-normal': '--tracking-normal',
      'text-letter-wide': '--tracking-wide',
    };
    for (const token of dictionary.allTokens) {
      const target = renames[token.name] ?? `--${token.name}`;
      lines.push(`  ${target}: var(--${token.name});`);
    }
    lines.push('}', '');
    return lines.join('\n');
  },
});

const sd = new StyleDictionary(config);
sd.buildAllPlatforms().catch((err) => {
  console.error('tokens:build failed', err);
  process.exit(1);
});
