"""init

Revision ID: 6795c61af3e1
Revises: 
Create Date: 2026-06-22 00:32:58.099484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6795c61af3e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('map_id', sa.String(length=64), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('world_state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('role_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('default_speaker_id', sa.String(length=64), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('avatar_blob', sa.LargeBinary(), nullable=True),
    sa.Column('avatar_mime_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uix_user_role_name')
    )
    op.create_index(op.f('ix_role_profiles_is_builtin'), 'role_profiles', ['is_builtin'], unique=False)
    op.create_index(op.f('ix_role_profiles_user_id'), 'role_profiles', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uix_user_setting_key')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_table('actor_minds',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('relations_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('memories_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('goal_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inventory_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'actor_id')
    )
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('intra_turn_seq', sa.Integer(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('speak', sa.Text(), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('act_patch_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'turn_id', 'intra_turn_seq', name='uix_timeline_turn_seq')
    )
    op.create_index('ix_timeline_conversation_id', 'timeline', ['conversation_id', 'id'], unique=False)
    op.create_table('tts_voice_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('speaker_id', sa.String(length=64), nullable=True),
    sa.Column('audio_uri', sa.String(length=512), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_voice_cache_conversation_id'), 'tts_voice_cache', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tts_voice_cache_status'), 'tts_voice_cache', ['status'], unique=False)
    op.create_index(op.f('ix_tts_voice_cache_text_hash'), 'tts_voice_cache', ['text_hash'], unique=False)
    op.create_index(op.f('ix_tts_voice_cache_user_id'), 'tts_voice_cache', ['user_id'], unique=False)
    op.create_table('world_digests',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('at_version', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_digests')
    op.drop_index(op.f('ix_tts_voice_cache_user_id'), table_name='tts_voice_cache')
    op.drop_index(op.f('ix_tts_voice_cache_text_hash'), table_name='tts_voice_cache')
    op.drop_index(op.f('ix_tts_voice_cache_status'), table_name='tts_voice_cache')
    op.drop_index(op.f('ix_tts_voice_cache_conversation_id'), table_name='tts_voice_cache')
    op.drop_table('tts_voice_cache')
    op.drop_index('ix_timeline_conversation_id', table_name='timeline')
    op.drop_table('timeline')
    op.drop_table('actor_minds')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_role_profiles_user_id'), table_name='role_profiles')
    op.drop_index(op.f('ix_role_profiles_is_builtin'), table_name='role_profiles')
    op.drop_table('role_profiles')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
