"""add narration to timeline

Revision ID: 91a31990f9df
Revises: 6795c61af3e1
Create Date: 2026-07-16 16:56:27.821980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a31990f9df'
down_revision: Union[str, Sequence[str], None] = '6795c61af3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column('narration', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline', 'narration')
    # ### end Alembic commands ###
