name: frontend-ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/frontend-with-openapi
      - run: pnpm typecheck
        working-directory: frontend
      - run: pnpm lint
        working-directory: frontend
      - run: pnpm format:check
        working-directory: frontend
      - run: pnpm check:assets
        working-directory: frontend
      - run: pnpm test
        working-directory: frontend
      - run: pnpm build
        working-directory: frontend
      - run: pnpm test:e2e:install
        working-directory: frontend
      - run: pnpm build-storybook
        working-directory: frontend
      - run: pnpm test:e2e
        working-directory: frontend
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7
